#!/usr/bin/env python3

import argparse
import io
import socket
import tempfile
import threading
import gi
import setproctitle
import zmq

from PIL import Image

gi.require_version('Notify', '0.7')

from gi.repository import Notify

setproctitle.setproctitle("a2ln")

argumentParser = argparse.ArgumentParser(description="Shows Android notifications on Linux")

argumentParser.add_argument("port", metavar="p", type=int, help="The port")

def send_notification(title, text, picture_file=None):
    if picture_file is None:
        Notify.Notification.new(title, text, "dialog-information").show()
    else:
        Notify.Notification.new(title, text, picture_file.name).show()

        picture_file.close()

    print(f"Sent notification (Title: {title}, Text: {text})")

port = argumentParser.parse_args().port

with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as socket:
    socket.connect(("8.8.8.8", 80))

    print(f"Address: {socket.getsockname()[0]}:{port}")

with zmq.Context() as context, context.socket(zmq.PULL) as socket:
    socket.bind(f"tcp://*:{port}")

    Notify.init("Android 2 Linux Notifications")

    while True:
        try:
            notification = socket.recv_multipart()
        except KeyboardInterrupt:
            break

        if len(notification) < 2:
            continue

        title = notification[0].decode("utf-8")
        text = notification[1].decode("utf-8")

        if len(notification) > 2:
            picture_file = tempfile.NamedTemporaryFile(suffix=".png")

            Image.open(io.BytesIO(notification[2])).save(picture_file.name)

            args = (title, text, picture_file)
        else:
            args = (title, text)

        threading.Thread(target=send_notification, args=args).start()
