#!/usr/bin/env python3

import argparse
import io
import tempfile
import threading
import gi
import setproctitle
import zmq

from PIL import Image

gi.require_version('Notify', '0.7')

from gi.repository import Notify


def parse_args():
    argument_parser = argparse.ArgumentParser(description="Shows Android notifications on Linux")

    argument_parser.add_argument("port", metavar="p", type=int, help="The port")

    return argument_parser.parse_args()


def send_notification(title, text, picture_file=None):
    if picture_file is None:
        Notify.Notification.new(title, text, "dialog-information").show()
    else:
        Notify.Notification.new(title, text, picture_file.name).show()

        picture_file.close()

    print(f"Sent notification (Title: {title}, Text: {text})")


def handle_notification(notification):
    if len(notification) < 2:
        return

    title = notification[0].decode("utf-8")
    text = notification[1].decode("utf-8")

    if len(notification) > 2:
        picture_file = tempfile.NamedTemporaryFile(suffix=".png")

        Image.open(io.BytesIO(notification[2])).save(picture_file.name)

        args = (title, text, picture_file)
    else:
        args = (title, text)

    threading.Thread(target=send_notification, args=args).start()


def start():
    setproctitle.setproctitle("a2ln")

    port = parse_args().port

    with zmq.Context() as context, context.socket(zmq.PULL) as socket:
        socket.bind(f"tcp://*:{port}")

        Notify.init("Android 2 Linux Notifications")

        while True:
            try:
                handle_notification(socket.recv_multipart())
            except KeyboardInterrupt:
                break


start()
